dist: trusty
sudo: false

language: node_js
node_js:
  - "node"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"
branches:
  only:
    - master

obs:
  include:
    - stage: test
      script:
        - node test
        - yarn install
        - echo Hello World
    - stage: test2
      script:
        - node test
        - node test
        - yarn functions:install
        - yarn build- stage: test3
    - stage: test3
      script:
        - node test
        - node test
        - yarn functions:install
        - yarn build
    - stage: test4
      script:
        - node test
        - node test
        - yarn functions:install
        - yarn build
    - stage: test5
      script:
        - node test
        - node test
        - yarn functions:install
        - yarn build

stages:
  - test
  - test2
  - test3
  - test4
  - test5
